name: Learning-Github-Actions-CI-Pipeline
run-name: ${{ github.actor }} is learing github actions
on: [push]
jobs:
 First-workflow:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: secret scanning
        run: echo "secret scan"
      - name: sast
        run: echo "performing sast"
      - name: sca
        run: echo "performing sca"
      - name: docker scan
        run: echo "performing docker scan"
